{
 "title": "Food Delivery Backend Metrics",
 "tags": [
  "backend",
  "nodejs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Heap Used" },
    { "expr": "nodejs_heap_size_total_bytes", "legendFormat": "Heap Total" }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m])",
     "legendFormat": "User CPU"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total[1m])",
     "legendFormat": "System CPU"
    }
   ]
  },
  {
   "title": "External Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_external_memory_bytes", "legendFormat": "External Memory" }
   ]
  }
 ]
}